// Only import what you actually use to improve tree shaking
export {
  Box,
  Container,
  Typography,
  Button,
  Card,
  CardContent,
  Grid,
  Chip,
  CircularProgress,
  LinearProgress,
  TextField,
  Alert,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  AppBar,
  Toolbar,
  IconButton,
  Menu,
  MenuItem,
  Tabs,
  Tab,
  Collapse,
  FormControl,
  InputLabel,
  Select,
  RadioGroup,
  FormControlLabel,
  Radio,
  Divider,
  Paper,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  Checkbox,
  Avatar,
  Tooltip
} from '@mui/material';

// Separate icons to their own chunk
export {
  Add as AddIcon,
  ExpandMore as ExpandMoreIcon,
  ExpandLess as ExpandLessIcon,
  CheckCircle as CheckCircleIcon,
  RadioButtonUnchecked as RadioButtonUncheckedIcon,
  YouTube as YouTubeIcon,
  VideoFile as VideoFileIcon,
  Edit as EditIcon,
  Refresh as RefreshIcon,
  Delete as DeleteIcon,
  PlayArrow as PlayArrowIcon,
  PlayCircleOutline,
  Lock,
  Visibility,
  VisibilityOff,
  Dashboard as DashboardIcon,
  PlaylistPlay,
  Schedule as ScheduleIcon,
  AccountCircle,
  ArrowBack as ArrowBackIcon,
  LogOut,
  PlayCircle,
  BarChart3
} from '@mui/icons-material';